DishoomItDjango/DishoomItDjango/urls.py
from django.conf.urls import patterns, include, url
import autocomplete_light
# import every app/autocomplete_light_registry.py
autocomplete_light.autodiscover()
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DishoomItDjango.views.home', name='home'),
    # url(r'^index/$', include('DishoomIt.views.index')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'DishoomIt.views.index'),
    url(r'^index/$', 'DishoomIt.views.index'),
    
    url(r'^login/$', 'DishoomIt.views.login'),
    url(r'^auth/$', 'DishoomIt.views.auth_view'),
    url(r'^logout/$', 'DishoomIt.views.logout'),
    #url(r'^loggedin/$', 'DishoomIt.views.loggedin'),
    url(r'^invalid/$', 'DishoomIt.views.invalid_login'),
    
    url(r'^starts_with/(?P<alphabet>.+)/dish/(?P<dish_id>\d+)/$', 'DishoomIt.views.alphabet_dish'),
    url(r'^starts_with/(?P<alphabet>.+)/$', 'DishoomIt.views.alphabet'),
    url(r'^submit/$', 'DishoomIt.views.submit'),
    url(r'^auto/', include('autocomplete_light.urls')),
    
)

DishoomItDjango/DishoomIt/forms.py
'''
Created on Feb 3, 2014

@author: hrishikeshrajpathak
'''

from django import forms

import autocomplete_light

from .models import Restaurant

RATING_CHOICES = (
     ('1', "--"),
     ('2', "1 (very bad)"),
     ('3', "2 (bad)"),
     ('4', "3 (average)"),
     ('5', "4 (good)"),
     ('6', "5 (excellent)"),
 )


class RestaurantForm(forms.Form):
    restaurant = forms.ModelChoiceField(
                    Restaurant.objects.all(),
                    label="Restaurant Name",
                    widget=autocomplete_light.ChoiceWidget(
                       'RestaurantAutocomplete',
                        attrs={
                            'class':'form-control',
                            'style':'width:100%;',
                            'id':'restaurant'
                            }
                        )
                    )
    menu_name = forms.CharField(label='Name on Menu (optional)', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    rating = forms.ChoiceField(label='Rating', choices=RATING_CHOICES,
                               widget=forms.Select(attrs={'class':'form-control'}))


class RestaurantFormNew(forms.Form):
    restaurant = forms.CharField(label='Restaurant Name', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control', 'id':'restaurant'}))
    menu_name = forms.CharField(label='Name on Menu (optional)', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    street = forms.CharField(label='Street (optional)', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    area = forms.CharField(label='Area', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    rating = forms.ChoiceField(label='Rating', choices=RATING_CHOICES,
                               widget=forms.Select(attrs={'class':'form-control'}))
    

class DishForm(forms.Form):
    dish_name = forms.CharField(label='Dish Name', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    restaurant = forms.ModelChoiceField(
                    Restaurant.objects.all(),
                    label="Restaurant Name",
                    widget=autocomplete_light.ChoiceWidget(
                       'RestaurantAutocomplete',
                        attrs={
                            'class':'form-control',
                            'style':'width:100%;',
                            'id':'restaurant'
                            }
                        )
                    )
    menu_name = forms.CharField(label='Name on Menu (optional)', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    rating = forms.ChoiceField(label='Rating', choices=RATING_CHOICES,
                               widget=forms.Select(attrs={'class':'form-control'}))
    
    
class DishFormNew(forms.Form):
    dish_name = forms.CharField(label='Dish Name', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    restaurant = forms.CharField(label='Restaurant Name', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control', 'id':'restaurant'}))
    menu_name = forms.CharField(label='Name on Menu (optional)', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    street = forms.CharField(label='Street (optional)', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    area = forms.CharField(label='Area', max_length=64,
                                widget=forms.TextInput(attrs={'class':'form-control'}))
    rating = forms.ChoiceField(label='Rating', choices=RATING_CHOICES,
                               widget=forms.Select(attrs={'class':'form-control'}))

DishoomItDjango/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>DishoomIt Pre-Launch Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="{% static "style.css" %}" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery.js"></script>
  	<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
  	<script src="{% static "js/bootstrap.min.js" %}"></script>
	{% include 'autocomplete_light/static.html' %}
    
	<script>
		function validateForm(eventObj) {
			var parentForm = $(eventObj.target).parents('form'), isValid = true;
			var selectRestValue = $('#rest_form #restaurant').val();
			var restInput = $('#rest_form #restaurant_text').val();
			if((selectRestValue == null || selectRestValue.length == 0) && (restInput != null && restInput.length == 0)) {
				isValid = false;
			}
			
			if($('#rest_form #id_rating').val() === "1") {
				isValid = false;
			}
			
			if(isValid) {
				parentForm.children(':button[type="submit"]').prop("disabled", false);
			} else {
				parentForm.children(':button[type="submit"]').prop("disabled", true);
			}
		}
		
		
		function validateDishForm(eventObj) {
			var parentForm = $(eventObj.target).parents('form'), isValid = true;
			var selectRestValue = $('#sidebarform #restaurant').val();
			var restInput = $('#sidebarform #restaurant_text').val();
			
			if ($("#sidebarform #id_dish_name").val().length == 0) {
				isValid = false;
			}
			
			if((selectRestValue == null || selectRestValue.length == 0) && (restInput != null && restInput.length == 0)) {
				isValid = false;
			}
			
			if($('#sidebarform #id_rating').val() === "1") {
				isValid = false;
			}
			
			if(isValid) {
				parentForm.children(':button[type="submit"]').prop("disabled", false);
			} else {
				parentForm.children(':button[type="submit"]').prop("disabled", true);
			}
		}

	    $(document).ready(function(){
			$("form :button[type='submit']").prop("disabled", true);
			$("#rest_form :input:not(:button)").change(validateForm);
			$("#sidebarform :input:not(:button)").change(validateDishForm);
	    }); 
    </script>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{% static "img/favicon.png" %}">
  </head>
  <body>
    
    <div class="container">

      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <img id="logo" src="{% static "img/logo.png" %}">
          <p class="navbar-text"><strong>Hi, {{ usernamee }}!</strong> &mdash; {{ user_msg }}</p>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/logout/">Log Out</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
      
      <div id="content" class="row">
        <div id="main" class="col-md-9">
          <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <p><strong>Please read this before you start:</strong></p>
            <ol>
              <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
              <li>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
              <li>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</li>
              <li>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
            </ol>
          </div>
          
          <div class="row">
            <div class="col-md-1">
              <ul>
                {% for char in array %}
                	{% if char == alphabet %}
                		<li class="active"><a href="/starts_with/{{ char }}/">{{ char }}</a></li>
                	{% else %}
                		<li><a href="/starts_with/{{ char }}/">{{ char }}</a></li>
                	{% endif %}
                {% endfor %}
              </ul>
            </div><!-- /alphabets -->
            
            <div class="col-md-3">
              <ul>
              	{% for dish in dishes %}
              		{% if dish.id == active_id %}
              		<li class="active"><a href="/starts_with/{{ alphabet }}/dish/{{ dish.id }}/">{{ dish.name }}</a></li>
              		{% else %}
              		<li><a href="/starts_with/{{ alphabet }}/dish/{{ dish.id }}/">{{ dish.name }}</a></li>
              		{% endif %}
              	{% endfor %}
              </ul>
            </div><!-- /dishes -->
            
            <div class="col-md-5">
              	{% for dish in dishes %}
              		{% if dish.id == active_id %}
              		<h3>{{ dish.name }}</h3>
              		{% endif %}
              	{% endfor %}
              <ul>
              	{% if menus|length < 1 %}
                	<li><i class="fa fa-exclamation-circle"></i> None rated yet.</li>
                {% else %}
	                {% for menu in menus %}
		              	<li>{{ menu.dish_ref.name }} @ {{ menu.rest_ref.name }} &mdash; {{ menu.rating }}/5</li>
		             {% endfor %}
		        {% endif %}
              </ul>
                {% if error %}
                	<p style="color:red">{{ error }}</p>
                {% endif %}
	             <form role="form" action="/submit/" method="post" id="rest_form">
	              	{% csrf_token %}
	              	{% for field in form %}
		              	<div class="form-group">
			              	{{ field.label_tag }}
			              	{{ field }}
		              	</div>
	              	{% endfor %}
	              	<input type="hidden" name="alphabet" value=" {{ alphabet }} ">
	                <input type="hidden" name="active_id" value=" {{ active_id }} ">
	                <input type="hidden" name="formtype" value=" {{ formtype }} ">
	                <input type="hidden" name="location" value="main">
	                <button type="submit" id="submit" class="btn btn-primary btn-block" disabled><i class="fa fa-check-circle"></i> Save</button>
	              </form>
              <!-- <form role="form" action="/submit/" method="post">{% csrf_token %}
                <div class="form-group">
                  <label for="restSearch">Restaurant Name</label>
                  <input type="text" name="restaurant" class="form-control" id="restSearch">
                </div>
                <div class="form-group">
                  <label for="rests">Name on Menu</label>
                  <input type="text" name="menu" class="form-control" id="rests">
                </div>
                <input type="hidden" name="alphabet" value=" {{ alphabet }} ">
                <input type="hidden" name="active_id" value=" {{ active_id }} ">
                <div class="form-group">
                  <label for="">Rating</label>
                  <select class="form-control" name="rating">
                    <option>--</option>
                    <option>1 (very bad)</option>
                    <option>2 (bad)</option>
                    <option>3 (average)</option>
                    <option>4 (good)</option>
                    <option>5 (excellent)</option>
                  </select>
                </div>
               <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-check-circle"></i> Save</button>
              </form> -->
            </div><!-- /dish -->
          </div>
        </div><!-- /#main -->
        <div id="sidebar" class="col-md-3">
          <div class="well" data-spy="affix" data-offset-top="0">
            <p>Have a very specific dish in mind that you&rsquo;d like to rate?</p>
            <button type="button" class="btn btn-block btn-default" data-toggle="collapse" data-target="#specific">Add</button>
            <!-- <div id="specific" class="collapse"> -->
              {% if sideerror %}
              		<div id="specific"> 
                	<p style="color:red">{{ sideerror }}</p>
              {% else %}
              		<div id="specific" class="collapse">
              {% endif %}
	             <form role="form" action="/submit/" method="post" id="sidebarform">
	              	{% csrf_token %}
	              	{% for field in sidebarform %}
		              	<div class="form-group">
			              	{{ field.label_tag }}
			              	{{ field }}
		              	</div>
	              	{% endfor %}
	              	<input type="hidden" name="alphabet" value=" {{ alphabet }} ">
	                <input type="hidden" name="active_id" value=" {{ active_id }} ">
	                <input type="hidden" name="formtype" value=" {{ formtype }} ">
	                <input type="hidden" name="location" value="sidebar">
	                <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-check-circle"></i> Save</button>
	             </form>
            </div>
          </div>
        </div><!-- /#sidebar -->
        <div id="footer" class="col-md-12">
          <p>&copy; 2014 &mdash; Se7en Labs</p>
        </div>
      </div><!-- /.row -->

    </div><!-- /.container -->
  </body>
</html>

DishoomItDjango/templates/invalid_login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
Wrong username  or passoword
</body>
</html>

DishoomItDjango/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>DishoomIt Pre-Launch Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="{% static "style.css" %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{% static "img/favicon.png" %}>
  </head>
  <body>
    
    <div class="container">

      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <img id="logo" src="{% static "img/logo.png" %}">
        </div><!-- /.navbar-collapse -->
      </nav>
      
      <div id="content" class="row">
        <div class="col-md-3">
          <form role="form" id="login" action="/auth/" method="post">{% csrf_token %}
            <div class="form-group">
              <label for="username">Username</label>
              <input type="text" class="form-control" id="username" name="username" value="">
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" value="" name="password" id="password">
            </div>
            <button type="submit" value="login" class="btn btn-primary" disabled>Login <i class="fa fa-arrow-circle-right"></i></button>
            <button type="submit" value="login" class="btn btn-primary">Login <i class="fa fa-arrow-circle-right"></i></button>
          </form>
        </div>
        <div id="footer" class="col-md-12">
          <p>&copy; 2014 &mdash; Se7en Labs</p>
        </div>
      </div><!-- /.row -->

    </div><!-- /.container -->

    <!-- javascript -->
<!--     <script src="https://code.jquery.com/jquery.js"></script>
    <script src="http://twitter.github.io/typeahead.js/releases/latest/typeahead.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script>
      $('input').typeahead({
        name: 'dishes',
        local: ['Butter Chicken', 'BBQ Chicken Wings', 'BBC', 'Bjkajlkasldisyeliuahelifuhau', 'Bur8hiwufh', 'Paneer Tikka Masala', 'Ras Malai']
      });
    </script> -->
  </body>
</html>

DishoomItDjango/templates/no-dish.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>DishoomIt Pre-Launch Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="{% static "style.css" %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.js" type="text/javascript"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
	{% include 'autocomplete_light/static.html' %}
    
    <script>
		function validateForm(eventObj) {
			var parentForm = $(eventObj.target).parents('form'), isValid = true;
			var selectRestValue = $('#rest_form #restaurant').val();
			var restInput = $('#rest_form #restaurant_text').val();
			if((selectRestValue == null || selectRestValue.length == 0) && (restInput != null && restInput.length == 0)) {
				isValid = false;
			}
			
			if($('#rest_form #id_rating').val() === "1") {
				isValid = false;
			}
			
			if(isValid) {
				parentForm.children(':button[type="submit"]').prop("disabled", false);
			} else {
				parentForm.children(':button[type="submit"]').prop("disabled", true);
			}
		}
		
		
		function validateDishForm(eventObj) {
			var parentForm = $(eventObj.target).parents('form'), isValid = true;
			var selectRestValue = $('#sidebarform #restaurant').val();
			var restInput = $('#sidebarform #restaurant_text').val();
			
			if ($("#sidebarform #id_dish_name").val().length == 0) {
				isValid = false;
			}
			
			if((selectRestValue == null || selectRestValue.length == 0) && (restInput != null && restInput.length == 0)) {
				isValid = false;
			}
			
			if($('#sidebarform #id_rating').val() === "1") {
				isValid = false;
			}
			
			if(isValid) {
				parentForm.children(':button[type="submit"]').prop("disabled", false);
			} else {
				parentForm.children(':button[type="submit"]').prop("disabled", true);
			}
		}
	
	    $(document).ready(function(){
			$("form :button[type='submit']").prop("disabled", true);
			$("#rest_form :input:not(:button)").change(validateForm);
			$("#sidebarform :input:not(:button)").change(validateDishForm);
	    }); 
    </script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{% static "img/favicon.png" %}">
  </head>
  <body>
    
    <div class="container">

      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <img id="logo" src="{% static "img/logo.png" %}">
          <p class="navbar-text"><strong>Hi, {{ usernamee }}!</strong> &mdash; {{ user_msg }}</p>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/logout/">Log Out</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
      
      <div id="content" class="row">
        <div id="main" class="col-md-9">
          <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <p><strong>Please read this before you start:</strong></p>
            <ol>
              <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
              <li>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
              <li>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</li>
              <li>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
            </ol>
          </div>
          
          <div class="row">
            <div class="col-md-1">
              <ul>
                {% for char in array %}
                	{% if char == alphabet %}
                		<li class="active"><a href="/starts_with/{{ char }}/">{{ char }}</a></li>
                	{% else %}
                		<li><a href="/starts_with/{{ char }}/">{{ char }}</a></li>
                	{% endif %}
                {% endfor %}
              </ul>
            </div><!-- /alphabets -->
            <div class="col-md-3">
              <p>There are currently no dishes starting with <strong>{{ alphabet }}</strong>. If you know any, please add them? Thank you! :)</p>
            </div><!-- /dishes -->
            <div class="col-md-5">
              <h3>Add a New Dish</h3>
              	{% if error %}
                	<p style="color:red">{{ error }}</p>
                {% endif %}
	             <form role="form" action="/submit/" method="post" id="rest_form">
	              	{% csrf_token %}
	              	{% for field in form %}
		              	<div class="form-group">
			              	{{ field.label_tag }}
			              	{{ field }}
		              	</div>
	              	{% endfor %}
	              	<input type="hidden" name="alphabet" value=" {{ alphabet }} ">
	                <input type="hidden" name="active_id" value=" {{ active_id }} ">
	                <input type="hidden" name="formtype" value=" {{ formtype }} ">
	                <input type="hidden" name="location" value="main">
	                <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-check-circle"></i> Save</button>
	              </form>
            </div><!-- /dish -->
          </div>
        </div><!-- /#main -->
        <div id="sidebar" class="col-md-3">
          <div class="well" data-spy="affix" data-offset-top="0">
            <p>Can&rsquo;t find a particular dish? Have a very specific dish in mind that you&rsquo;d like to rate?</p>
            <button type="button" class="btn btn-block btn-default" data-toggle="collapse" data-target="#specific">Add</button>
             <!-- <div id="specific" class="collapse"> -->
              {% if sideerror %}
              		<div id="specific"> 
                	<p style="color:red">{{ sideerror }}</p>
              {% else %}
              		<div id="specific" class="collapse">
              {% endif %}
	             <form role="form" action="/submit/" method="post" id="sidebarform">
	              	{% csrf_token %}
	              	{% for field in sidebarform %}
		              	<div class="form-group">
			              	{{ field.label_tag }}
			              	{{ field }}
		              	</div>
	              	{% endfor %}
	              	<input type="hidden" name="alphabet" value=" {{ alphabet }} ">
	                <input type="hidden" name="active_id" value=" {{ active_id }} ">
	                <input type="hidden" name="formtype" value=" {{ formtype }} ">
	                <input type="hidden" name="location" value="sidebar">
	                <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-check-circle"></i> Save</button>
	             </form>
            </div>
          </div>
        </div><!-- /#sidebar -->
        <div id="footer" class="col-md-12">
          <p>&copy; 2014 &mdash; Se7en Labs</p>
        </div>
      </div><!-- /.row -->

    </div><!-- /.container -->
  </body>
</html>